### ISSUE TITLE
JSDelivr Cache Purging Thread

### ISSUE THREAD

**Issue by avirtopeanu-ionos** [ionos-cloud/ui-driver-ionoscloud#12]

**Comment by avirtopeanu-ionos** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/ionos-cloud/ui-driver-ionoscloud@main/releases/latest/component.js

**Comment by avirtopeanu-ionos** [comment]
@jsdelivrbot purge https://cdn.jsdelivr.net/gh/ionos-cloud/ui-driver-ionoscloud@0.1.1/releases/v0.1.1/component.js

**Comment by jimaek** [comment]
Hey, the bot is not working at the moment, you need to use the API manually. Please email us for the instructions.
